# Generated by Django 5.2.5 on 2025-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conatct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reach_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('whatsap', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.CharField(max_length=50)),
                ('facebook', models.CharField(max_length=50)),
                ('tiktok', models.CharField(max_length=50)),
                ('location', models.URLField(max_length=100)),
            ],
        ),
    ]
