# Generated by Django 5.2.5 on 2025-09-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Conatact',
        ),
    ]
