# Generated by Django 5.2.5 on 2025-09-30 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0002_rename_conatct_conatact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatact',
            new_name='Contact',
        ),
    ]
