# Generated by Django 5.2.5 on 2025-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0003_rename_conatact_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reach_out',
            name='location_map',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reach_out',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
