# Generated by Django 5.2.5 on 2025-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0004_reach_out_location_map_alter_reach_out_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vilat/')),
                ('description', models.TextField()),
                ('sub_description1', models.TextField()),
                ('sub_description2', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('vendndodhja', models.CharField(max_length=50)),
                ('lloji', models.CharField(max_length=50)),
                ('sip_vila', models.CharField(max_length=50)),
                ('sip_parcela', models.CharField(max_length=50)),
                ('numri_tipologjive', models.CharField(max_length=50)),
                ('planimetria_img', models.ImageField(upload_to='vilat/')),
                ('kati_0_img', models.ImageField(upload_to='vilat/')),
                ('kati_1_img', models.ImageField(upload_to='vilat/')),
                ('kati_2_img', models.ImageField(upload_to='vilat/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
