# Generated by Django 5.2.5 on 2025-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0005_vilat'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=10)),
                ('title1', models.CharField(max_length=10)),
                ('description1', models.TextField()),
                ('title2', models.CharField(max_length=10)),
                ('description2', models.TextField()),
                ('title3', models.CharField(max_length=10)),
                ('description3', models.TextField()),
                ('title4', models.CharField(max_length=10)),
                ('description4', models.TextField()),
            ],
        ),
    ]
