# Generated by Django 5.2.5 on 2025-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0006_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='title2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='title3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='about',
            name='title4',
            field=models.CharField(max_length=20),
        ),
    ]
