# Generated by Django 5.2.5 on 2025-10-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0007_alter_about_title1_alter_about_title2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vilat',
            name='planimetria_img',
        ),
    ]
