# Generated by Django 5.2.5 on 2025-10-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0008_remove_vilat_planimetria_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vilat',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='vilat/'),
        ),
    ]
