# Generated by Django 5.2.5 on 2025-10-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0009_vilat_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vilat',
            name='cover',
        ),
    ]
