# Generated by Django 5.2.5 on 2025-10-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barkea_App', '0010_remove_vilat_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='vilat',
            name='main_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
